pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                echo 'Cleanign up workspace..'
                mvn clean
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                mvn install
            }
        }
        stage('Done..') {
            steps {
                echo 'Done....'

            }
        }
    }
}