pipeline {
    agent any

    stages {
        stage('Clean') {
            steps {
                echo 'Cleanign up workspace..'
                mvn clean
            }
        }
        stage('Build') {
            steps {
                echo 'Building..'
                mvn compile
            }
        }
        stage('Test') {
            steps {
                echo 'Testing....'
                mvn test
            }
        }
    }
}