version: '3.6'

services:
  oracle-db:
    image: epiclabs/docker-oracle-xe-11g
    ports:
      - 1521:1521
      - 5500:5500
      - 8080:8080
    volumes:
      - ./oracle/:/u01/app/oracle
      - ./oracle-sql:/docker-entrypoint-initdb.d/

    environment:
      - ORACLE_ENABLE_XDB=tru
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_DISABLE_ASYNCH_IO=true