version: '3.1'

services:

  db:
    image: webdizz/oracle-xe-11g-sa:latest
    ports:
      - "8080:8080"
      - "1521:1521"
    environment:
      - processes=200
      - DATABASES=sample
    volumes:
      - ./oracle:/u01/app/oracle
      - ./oracle-sql:/u01/app/oracle/scripts/startup


#system/oracle